version: "3.9"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile
   ports:
    -  "4200:4200"
   container_name: ui     
   volumes:   
    -  "./ui/src/:/ui/src/"      
   depends_on:
    - api 
  api:
   build:
      context: ./api
      dockerfile: Dockerfile
   ports:
     - "3000:3000"
   container_name: api   
  #  volumes:
  #   - "./api/:/api"
   depends_on:
    - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db    
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local